Fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1826,6 +1826,149 @@ jobs:
     - REPEATED_UTEST_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
     - JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
     - JDK_HOME: /usr/lib/jvm/java-8-openjdk-amd64
+  j8_upgrade_dtests_repeat:
+    docker:
+    - image: apache/cassandra-testing-ubuntu2004-java11-w-dependencies:latest
+    resource_class: medium
+    working_directory: ~/
+    shell: /bin/bash -eo pipefail -l
+    parallelism: 4
+    steps:
+    - attach_workspace:
+        at: /home/cassandra
+    - run:
+        name: Clone Cassandra dtest Repository (via git)
+        command: |
+          git clone --single-branch --branch $DTEST_BRANCH --depth 1 $DTEST_REPO ~/cassandra-dtest
+    - run:
+        name: Configure virtualenv and python Dependencies
+        command: |
+          # note, this should be super quick as all dependencies should be pre-installed in the docker image
+          # if additional dependencies were added to requirmeents.txt and the docker image hasn't been updated
+          # we'd have to install it here at runtime -- which will make things slow, so do yourself a favor and
+          # rebuild the docker image! (it automatically pulls the latest requirements.txt on build)
+          source ~/env3.6/bin/activate
+          export PATH=$JAVA_HOME/bin:$PATH
+          pip3 install --exists-action w --upgrade -r ~/cassandra-dtest/requirements.txt
+          pip3 uninstall -y cqlsh
+          pip3 freeze
+    - run:
+        name: Run repeated Python dtest
+        no_output_timeout: 15m
+        command: |
+          if [ "${REPEATED_UPGRADE_DTEST_NAME}" == "<nil>" ]; then
+            echo "Repeated dtest name hasn't been defined, exiting without running any test"
+          elif [ "${REPEATED_UPGRADE_DTEST_COUNT}" == "<nil>" ]; then
+            echo "Repeated dtest count hasn't been defined, exiting without running any test"
+          elif [ "${REPEATED_UPGRADE_DTEST_COUNT}" -le 0 ]; then
+            echo "Repeated dtest count is lesser or equals than zero, exiting without running any test"
+          else
+
+            # Calculate the number of test iterations to be run by the current parallel runner.
+            # Since we are running the same test multiple times there is no need to use `circleci tests split`.
+            count=$((${REPEATED_UPGRADE_DTEST_COUNT} / CIRCLE_NODE_TOTAL))
+            if (($CIRCLE_NODE_INDEX < (${REPEATED_UPGRADE_DTEST_COUNT} % CIRCLE_NODE_TOTAL))); then
+              count=$((count+1))
+            fi
+
+            if (($count <= 0)); then
+              echo "No tests to run in this runner"
+            else
+              echo "Running ${REPEATED_UPGRADE_DTEST_NAME} $count times"
+
+              source ~/env3.6/bin/activate
+              export PATH=$JAVA_HOME/bin:$PATH
+
+              java -version
+              cd ~/cassandra-dtest
+              mkdir -p /tmp/dtest
+
+              echo "env: $(env)"
+              echo "** done env"
+              mkdir -p /tmp/results/dtests
+
+              stop_on_failure_arg=""
+              if ${REPEATED_UPGRADE_DTEST_STOP_ON_FAILURE}; then
+                stop_on_failure_arg="-x"
+              fi
+
+              vnodes_args=""
+              if false; then
+                vnodes_args="--use-vnodes --num-tokens=16"
+              fi
+
+              upgrade_arg=""
+              if true; then
+                upgrade_arg="--execute-upgrade-tests"
+              fi
+
+              # we need the "set -o pipefail" here so that the exit code that circleci will actually use is from pytest and not the exit code from tee
+              set -o pipefail && cd ~/cassandra-dtest && pytest $vnodes_args --count=$count $stop_on_failure_arg $upgrade_arg --log-cli-level=DEBUG --junit-xml=/tmp/results/dtests/pytest_result.xml -s --cassandra-dir=/home/cassandra/cassandra --keep-test-dir ${REPEATED_UPGRADE_DTEST_NAME} | tee /tmp/dtest/stdout.txt
+            fi
+          fi
+    - store_test_results:
+        path: /tmp/results
+    - store_artifacts:
+        path: /tmp/dtest
+        destination: dtest
+    - store_artifacts:
+        path: ~/cassandra-dtest/logs
+        destination: dtest_logs
+    environment:
+    - ANT_HOME: /usr/share/ant
+    - JAVA11_HOME: /usr/lib/jvm/java-11-openjdk-amd64
+    - JAVA8_HOME: /usr/lib/jvm/java-8-openjdk-amd64
+    - LANG: en_US.UTF-8
+    - KEEP_TEST_DIR: true
+    - DEFAULT_DIR: /home/cassandra/cassandra-dtest
+    - PYTHONIOENCODING: utf-8
+    - PYTHONUNBUFFERED: true
+    - CASS_DRIVER_NO_EXTENSIONS: true
+    - CASS_DRIVER_NO_CYTHON: true
+    - CASSANDRA_SKIP_SYNC: true
+    - CASSANDRA_REPO: https://github.com/apache/cassandra.git
+    - CASSANDRA_BRANCH: trunk
+    - DTEST_REPO: https://github.com/apache/cassandra-dtest.git
+    - DTEST_BRANCH: trunk
+    - CCM_MAX_HEAP_SIZE: 1024M
+    - CCM_HEAP_NEWSIZE: 256M
+    - REPEATED_TESTS_COUNT: 500
+    - REPEATED_TESTS_STOP_ON_FAILURE: false
+    - REPEATED_UTESTS: null
+    - REPEATED_UTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_UTESTS_FQLTOOL: null
+    - REPEATED_UTESTS_FQLTOOL_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UTESTS_FQLTOOL_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_UTESTS_LONG: null
+    - REPEATED_UTESTS_LONG_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UTESTS_LONG_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_UTESTS_STRESS: null
+    - REPEATED_UTESTS_STRESS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UTESTS_STRESS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_SIMULATOR_DTESTS: null
+    - REPEATED_SIMULATOR_DTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_SIMULATOR_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_JVM_DTESTS: null
+    - REPEATED_JVM_DTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_JVM_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_JVM_UPGRADE_DTESTS: null
+    - REPEATED_JVM_UPGRADE_DTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_JVM_UPGRADE_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_DTESTS: null
+    - REPEATED_DTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_UPGRADE_DTESTS: null
+    - REPEATED_UPGRADE_DTESTS_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UPGRADE_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - REPEATED_UTEST_TARGET: testsome
+    - REPEATED_UTEST_CLASS: null
+    - REPEATED_UTEST_METHODS: null
+    - REPEATED_UTEST_VNODES: false
+    - REPEATED_UTEST_COUNT: REPEATED_TESTS_COUNT
+    - REPEATED_UTEST_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
+    - JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
+    - JDK_HOME: /usr/lib/jvm/java-8-openjdk-amd64
   utests_system_keyspace_directory_repeat:
     docker:
     - image: apache/cassandra-testing-ubuntu2004-java11:latest
@@ -2545,7 +2688,7 @@ jobs:
     - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
     - JDK_HOME: /usr/lib/jvm/java-11-openjdk-amd64
     - CASSANDRA_USE_JDK11: true
-  j8_upgradetests-no-vnodes:
+  j8_upgrade_dtests:
     docker:
     - image: apache/cassandra-testing-ubuntu2004-java11-w-dependencies:latest
     resource_class: medium
@@ -4947,149 +5090,6 @@ jobs:
     - REPEATED_UTEST_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
     - JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
     - JDK_HOME: /usr/lib/jvm/java-8-openjdk-amd64
-  repeated_upgrade_dtests:
-    docker:
-    - image: apache/cassandra-testing-ubuntu2004-java11-w-dependencies:latest
-    resource_class: medium
-    working_directory: ~/
-    shell: /bin/bash -eo pipefail -l
-    parallelism: 4
-    steps:
-    - attach_workspace:
-        at: /home/cassandra
-    - run:
-        name: Clone Cassandra dtest Repository (via git)
-        command: |
-          git clone --single-branch --branch $DTEST_BRANCH --depth 1 $DTEST_REPO ~/cassandra-dtest
-    - run:
-        name: Configure virtualenv and python Dependencies
-        command: |
-          # note, this should be super quick as all dependencies should be pre-installed in the docker image
-          # if additional dependencies were added to requirmeents.txt and the docker image hasn't been updated
-          # we'd have to install it here at runtime -- which will make things slow, so do yourself a favor and
-          # rebuild the docker image! (it automatically pulls the latest requirements.txt on build)
-          source ~/env3.6/bin/activate
-          export PATH=$JAVA_HOME/bin:$PATH
-          pip3 install --exists-action w --upgrade -r ~/cassandra-dtest/requirements.txt
-          pip3 uninstall -y cqlsh
-          pip3 freeze
-    - run:
-        name: Run repeated Python dtest
-        no_output_timeout: 15m
-        command: |
-          if [ "${REPEATED_UPGRADE_DTEST_NAME}" == "<nil>" ]; then
-            echo "Repeated dtest name hasn't been defined, exiting without running any test"
-          elif [ "${REPEATED_UPGRADE_DTEST_COUNT}" == "<nil>" ]; then
-            echo "Repeated dtest count hasn't been defined, exiting without running any test"
-          elif [ "${REPEATED_UPGRADE_DTEST_COUNT}" -le 0 ]; then
-            echo "Repeated dtest count is lesser or equals than zero, exiting without running any test"
-          else
-
-            # Calculate the number of test iterations to be run by the current parallel runner.
-            # Since we are running the same test multiple times there is no need to use `circleci tests split`.
-            count=$((${REPEATED_UPGRADE_DTEST_COUNT} / CIRCLE_NODE_TOTAL))
-            if (($CIRCLE_NODE_INDEX < (${REPEATED_UPGRADE_DTEST_COUNT} % CIRCLE_NODE_TOTAL))); then
-              count=$((count+1))
-            fi
-
-            if (($count <= 0)); then
-              echo "No tests to run in this runner"
-            else
-              echo "Running ${REPEATED_UPGRADE_DTEST_NAME} $count times"
-
-              source ~/env3.6/bin/activate
-              export PATH=$JAVA_HOME/bin:$PATH
-
-              java -version
-              cd ~/cassandra-dtest
-              mkdir -p /tmp/dtest
-
-              echo "env: $(env)"
-              echo "** done env"
-              mkdir -p /tmp/results/dtests
-
-              stop_on_failure_arg=""
-              if ${REPEATED_UPGRADE_DTEST_STOP_ON_FAILURE}; then
-                stop_on_failure_arg="-x"
-              fi
-
-              vnodes_args=""
-              if false; then
-                vnodes_args="--use-vnodes --num-tokens=16"
-              fi
-
-              upgrade_arg=""
-              if true; then
-                upgrade_arg="--execute-upgrade-tests"
-              fi
-
-              # we need the "set -o pipefail" here so that the exit code that circleci will actually use is from pytest and not the exit code from tee
-              set -o pipefail && cd ~/cassandra-dtest && pytest $vnodes_args --count=$count $stop_on_failure_arg $upgrade_arg --log-cli-level=DEBUG --junit-xml=/tmp/results/dtests/pytest_result.xml -s --cassandra-dir=/home/cassandra/cassandra --keep-test-dir ${REPEATED_UPGRADE_DTEST_NAME} | tee /tmp/dtest/stdout.txt
-            fi
-          fi
-    - store_test_results:
-        path: /tmp/results
-    - store_artifacts:
-        path: /tmp/dtest
-        destination: dtest
-    - store_artifacts:
-        path: ~/cassandra-dtest/logs
-        destination: dtest_logs
-    environment:
-    - ANT_HOME: /usr/share/ant
-    - JAVA11_HOME: /usr/lib/jvm/java-11-openjdk-amd64
-    - JAVA8_HOME: /usr/lib/jvm/java-8-openjdk-amd64
-    - LANG: en_US.UTF-8
-    - KEEP_TEST_DIR: true
-    - DEFAULT_DIR: /home/cassandra/cassandra-dtest
-    - PYTHONIOENCODING: utf-8
-    - PYTHONUNBUFFERED: true
-    - CASS_DRIVER_NO_EXTENSIONS: true
-    - CASS_DRIVER_NO_CYTHON: true
-    - CASSANDRA_SKIP_SYNC: true
-    - CASSANDRA_REPO: https://github.com/apache/cassandra.git
-    - CASSANDRA_BRANCH: trunk
-    - DTEST_REPO: https://github.com/apache/cassandra-dtest.git
-    - DTEST_BRANCH: trunk
-    - CCM_MAX_HEAP_SIZE: 1024M
-    - CCM_HEAP_NEWSIZE: 256M
-    - REPEATED_TESTS_COUNT: 500
-    - REPEATED_TESTS_STOP_ON_FAILURE: false
-    - REPEATED_UTESTS: null
-    - REPEATED_UTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_UTESTS_FQLTOOL: null
-    - REPEATED_UTESTS_FQLTOOL_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UTESTS_FQLTOOL_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_UTESTS_LONG: null
-    - REPEATED_UTESTS_LONG_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UTESTS_LONG_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_UTESTS_STRESS: null
-    - REPEATED_UTESTS_STRESS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UTESTS_STRESS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_SIMULATOR_DTESTS: null
-    - REPEATED_SIMULATOR_DTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_SIMULATOR_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_JVM_DTESTS: null
-    - REPEATED_JVM_DTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_JVM_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_JVM_UPGRADE_DTESTS: null
-    - REPEATED_JVM_UPGRADE_DTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_JVM_UPGRADE_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_DTESTS: null
-    - REPEATED_DTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_UPGRADE_DTESTS: null
-    - REPEATED_UPGRADE_DTESTS_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UPGRADE_DTESTS_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - REPEATED_UTEST_TARGET: testsome
-    - REPEATED_UTEST_CLASS: null
-    - REPEATED_UTEST_METHODS: null
-    - REPEATED_UTEST_VNODES: false
-    - REPEATED_UTEST_COUNT: REPEATED_TESTS_COUNT
-    - REPEATED_UTEST_STOP_ON_FAILURE: REPEATED_TESTS_STOP_ON_FAILURE
-    - JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
-    - JDK_HOME: /usr/lib/jvm/java-8-openjdk-amd64
   j11_unit_tests_repeat:
     docker:
     - image: apache/cassandra-testing-ubuntu2004-java11:latest
@@ -6080,9 +6080,11 @@ workflows:
         requires:
         - start_j8_jvm_dtests
         - j8_build
+    - start_j8_jvm_dtests_vnode:
+        type: approval
     - j8_jvm_dtests_vnode:
         requires:
-        - start_j8_jvm_dtests
+        - start_j8_jvm_dtests_vnode
         - j8_build
     - start_j8_jvm_dtests_repeat:
         type: approval
@@ -6228,11 +6230,11 @@ workflows:
         requires:
         - start_j11_dtests_vnode
         - j8_build
-    - start_upgrade_tests:
+    - start_upgrade_dtests:
         type: approval
-    - j8_upgradetests-no-vnodes:
+    - j8_upgrade_dtests:
         requires:
-        - start_upgrade_tests
+        - start_upgrade_dtests
         - j8_build
     - start_j8_cqlsh_tests:
         type: approval
@@ -6306,11 +6308,11 @@ workflows:
         requires:
         - start_j11_dtests_vnode_repeat
         - j8_build
-    - start_repeated_upgrade_dtests:
+    - start_j8_upgrade_dtests_repeat:
         type: approval
-    - repeated_upgrade_dtests:
+    - j8_upgrade_dtests_repeat:
         requires:
-        - start_repeated_upgrade_dtests
+        - start_j8_upgrade_dtests_repeat
         - j8_build
   java8_pre-commit_tests:
     jobs:
@@ -6413,21 +6415,39 @@ workflows:
     - j8_dtests:
         requires:
         - j8_build
+    - j8_dtests_repeat:
+        requires:
+        - j8_build
     - j8_dtests_vnode:
+        requires:
+        - j8_build
+    - j8_dtests_vnode_repeat:
         requires:
         - j8_build
     - j11_dtests:
         requires:
         - j8_build
+    - j11_dtests_repeat:
+        requires:
+        - j8_build
     - j11_dtests_vnode:
         requires:
         - j8_build
-    - start_upgrade_tests:
-        type: approval
-    - j8_upgradetests-no-vnodes:
+    - j11_dtests_vnode_repeat:
         requires:
         - j8_build
-        - start_upgrade_tests
+    - start_upgrade_dtests:
+        type: approval
+    - j8_upgrade_dtests:
+        requires:
+        - j8_build
+        - start_upgrade_dtests
+    - start_upgrade_dtests_repeat:
+        type: approval
+    - j8_upgrade_dtests_repeat:
+        requires:
+        - j8_build
+        - start_upgrade_dtests
     - j8_cqlsh-dtests-py3-with-vnodes:
         requires:
         - j8_build
@@ -6463,36 +6483,6 @@ workflows:
     - j11_repeated_utest:
         requires:
         - start_j11_repeated_utest
-        - j8_build
-    - start_j8_dtests_repeat:
-        type: approval
-    - j8_dtests_repeat:
-        requires:
-        - start_j8_dtests_repeat
-        - j8_build
-    - start_j8_dtests_vnode_repeat:
-        type: approval
-    - j8_dtests_vnode_repeat:
-        requires:
-        - start_j8_dtests_vnode_repeat
-        - j8_build
-    - start_j11_dtests_repeat:
-        type: approval
-    - j11_dtests_repeat:
-        requires:
-        - start_j11_dtests_repeat
-        - j8_build
-    - start_j11_dtests_vnode_repeat:
-        type: approval
-    - j11_dtests_vnode_repeat:
-        requires:
-        - start_j11_dtests_vnode_repeat
-        - j8_build
-    - start_repeated_upgrade_dtests:
-        type: approval
-    - repeated_upgrade_dtests:
-        requires:
-        - start_repeated_upgrade_dtests
         - j8_build
   java11_separate_tests:
     jobs:
